### ISSUE TITLE
Can't take working SSO via SAML2.0 on AD FS

### ISSUE THREAD

**Issue by luter24** [derricksmith/phpsaml#119]
Hello.
What Relying party SAML 2.0 SSO service URL must i use to make it works?
In Docs it is `<GLPI home path>/plugins/phpsaml/front/acs.php`, but with this URL SSO with my AD FS not working.

**Comment by luter24** [comment]
Still have no solution for this problem...
 Also start to get error messages on ADFS log:
"Log Name:      AD FS Tracing/Debug
Source:        AD FS Tracing
Date:          05.12.2022 9:47:57
Event ID:      153
Task Category: None
Level:         Error
Keywords:      ADFSPassivePipeline
User:          RS\stsaccount$
Computer:      adfssrv1.russian.space
Description:
Exception: MSIS7007: The requested relying party trust 'http://glpi.russian.space/' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
StackTrace:    at Microsoft.IdentityServer.Web.Protocols.Saml.SamlSignInContext.ValidateCore()
   at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="AD FS Tracing" Guid="{0457a490-4d4d-4a5b-b639-35382f1b6709}" />
    <EventID>153</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000004000000</Keywords>
    <TimeCreated SystemTime="2022-12-05T06:47:57.618457800Z" />
    <EventRecordID>12</EventRecordID>
    <Correlation ActivityID="{f34a67c4-dba7-4452-32d7-0080000000c9}" />
    <Execution ProcessID="8132" ThreadID="10360" ProcessorID="0" KernelTime="0" UserTime="0" />
    <Channel>AD FS Tracing/Debug</Channel>
    <Computer>adfssrv1.russian.space</Computer>
    <Security UserID="S-1-5-21-3303566778-1856894434-1258699743-1679" />
  </System>
  <UserData>
    <Event xmlns="http://schemas.microsoft.com/ActiveDirectoryFederationServices/2.0/Events">
      <EventData>Exception: MSIS7007: The requested relying party trust 'http://glpi.russian.space/' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
StackTrace:    at Microsoft.IdentityServer.Web.Protocols.Saml.SamlSignInContext.ValidateCore()
   at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
</EventData>
    </Event>
  </UserData>
</Event>"
